- name: common | include vars
  include_vars: ../vars/main.yml

- name: common | final touches | fish
  block:
    - name: common | final touches | fish | get binary location
      shell: which fish
      register: fish_shell

    - name: common | final touches | fish | check fish is in /etc/shells
      become: true
      lineinfile:
        path: /etc/shells
        line:  "{{ fish_shell.stdout }}"
        create: yes

    - name: common | final touches | fish | change default shell
      user:
        name: paolo
        shell: "{{ fish_shell.stdout }}"
        state: present
      become: true

- name: common | final touches | profile config
  lineinfile:
    path: ~/.zprofile
    line: "{{ item }}"
  loop:
    "{{ profile_customizations }}"

- name: common | final touches | alacritty
  block:
  - name: common | final touches | alacritty | cloning
    git:
      repo: https://github.com/catppuccin/alacritty.git
      dest: ~/.config/alacritty/catppuccin

  - name: common | final touches | alacritty | copying config copy
    copy:
      src: "{{ item }}"
      dest: ~/.config/alacritty/
    with_fileglob:
     -  "../files/config/alacritty/*"

- name: common | final touches | fish | config
  copy:
    src: "{{ item }}"
    dest: ~/.config/fish/
  with_fileglob:
    - "../files/config/fish/*"

- name: common | final touches | tmux
  block:
  - name: common | final touches | tmux | install tpm
    git:
      repo: "https://github.com/tmux-plugins/tpm"
      dest: ~/.config/tmux/plugins/tpm
      update: true

  - name: common | final touches | tmux | copy config
    copy:
      src: "{{ item }}"
      dest: ~/.config/tmux/
    with_fileglob:
     -  "../files/config/tmux/*"

  - name: common | final touches | tmux | set fish for tmux
    lineinfile:
      path: ~/.config/tmux/tmux.conf
      search_string: FISH_BIN
      line: set-option -g default-shell "{{ fish_shell.stdout }}"

- name: common | final touches | neovim
  block:
    - name: common | final touches | neovim | copy config
      copy:
        src: "{{ item }}"
        dest: ~/.config/nvim/
      with_fileglob:
        - "../files/config/nvim/*"


