import = [
  "~/.config/alacritty/catppuccin/catppuccin-mocha.toml"
]
live_config_reload = true
[shell]
program = "/opt/local/bin/fish"
args = [
  "--login"
]

[env]
TERM = "xterm-256color"

[window]
option_as_alt = "Both"
decorations = "buttonless"
dynamic_padding = false
opacity = 0.95

[window.padding]
x = 8
y = 8

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"
